# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
    provider "aws" {
        region = "us-east-1"
        assume_role {
          role_arn = "arn:aws:iam::324654522070:role/terraform-deployment-role"
        }
    }
