FROM golang:1.18 as builder

WORKDIR /go/src

COPY go.mod go.sum ./

RUN go mod download

COPY . .

RUN apt-get update && apt-get install build-essential librdkafka-dev -y

# RUN apt-get update && \
#   cd /tmp && git clone https://github.com/edenhill/librdkafka && \
#   cd librdkafka && git checkout tags/v2.0.2 && \
#   ./configure && make && make install && \
#   ldconfig &&\
#   cd ../ && rm -rf librdkafka

RUN go build -a -installsuffix cgo -o main ./cmd/main.go

FROM gcr.io/distroless/base

COPY --from=builder /go/src/main .
COPY --from=builder /go/src/.env .

USER nonroot:nonroot

CMD ["/main"]